package com.insiderser.android.calculator.test.rules

import android.content.Context
import androidx.test.core.app.ApplicationProvider
import com.insiderser.android.calculator.db.AppDatabase
import org.junit.rules.TestWatcher
import org.junit.runner.Description

/**
 * A JUnit rule that resets all tables before each test.
 *
 * This does NOT reset the auto-increment value generated by [androidx.room.PrimaryKey.autoGenerate].
 * After deleting the rows, Room will set a WAL checkpoint and run VACUUM.
 * This means that the data is completely erased.
 * The space will be reclaimed by the system if the amount surpasses
 * the threshold of database file size.
 */
class AppDatabaseRule : TestWatcher() {

    val db: AppDatabase by lazy {
        val context = ApplicationProvider.getApplicationContext<Context>()
        AppDatabase.create(context)
    }

    override fun starting(description: Description?) {
        db.clearAllTables()
    }
}
